apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-playground
  namespace: argocd
spec:
  project: default
  source:
    # chart: sealed-secrets
    repoURL: https://github.com/leobw/argocd-playground
    targetRevision: HEAD
    path: dev
    # helm:
    #   releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true